baseURL = "/"
title = "Site du mémoire"
languageCode = "fr"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"
