# Si site utilisateur : https://<pseudo>.github.io/
# Si site de projet :   https://<pseudo>.github.io/<nom-du-repo>/
baseURL = "<BASEURL>"
title = "Site du mémoire"
languageCode = "fr"
enableRobotsTXT = true
paginate = 10

# Utilise un thème via Hugo Modules (pas besoin de sous-module Git)
[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"

# Recommandé pour GitHub Pages : mettre le cache d'images au bon endroit
[caches]
  [caches.images]
    dir = ':cacheDir/images'
    
      - name: Init Hugo Modules (create go.mod if missing)
        run: |
          if [ ! -f go.mod ]; then
            hugo mod init github.com/${{ github.repository }}
          fi
          hugo mod get -u ./...
          hugo mod tidy
      - name: Cache Hugo/Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/hugo
            ~/go/pkg/mod
          key: modules-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            modules-
